[env:esp32]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.flash_size = 4MB
board_build.partitions = partitions.csv
board_build.psram = disabled
board_build.filesystem = littlefs
board_upload.flash_size = 4MB

build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
	symlink://../lib/init_print
	symlink://../lib/spi_helper
	symlink://../lib/display_transaction
	symlink://../lib/display_driver
	symlink://../lib/stream_reader
	greiman/SdFat
